import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {createHash,randomBytes} from 'node:crypto';
const base=process.env.TEST_URL||'http://localhost:3000';
if(!/^http:\/\/(localhost|127\.0\.0\.1):3000$/.test(base))throw new Error('Fixture tests run only against local preview.');
let passed=0;const users=[];const suffix=Date.now();
const sql=q=>JSON.parse(execFileSync('npx',['wrangler','d1','execute','togetherly-db','--local','--json','--command',q],{encoding:'utf8',cwd:process.cwd(),stdio:['ignore','pipe','pipe']}));
async function request(path,body,cookie='',method=body===undefined?'GET':'POST',origin=base){const r=await fetch(base+'/api'+path,{method,headers:{'Content-Type':'application/json','CF-Connecting-IP':`192.0.2.${1+suffix%254}`,Origin:origin,...(cookie?{Cookie:cookie}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}return{status:r.status,data,headers:r.headers,cookie:r.headers.get('set-cookie')?.split(';')[0]||cookie};}
const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};
try{
await test('health and launch gates',async()=>{assert.equal((await request('/health')).data.status,'ok');assert.equal((await request('/config')).data.payments_enabled,false);});
await test('anonymous private access denied',async()=>{assert.equal((await request('/profile')).status,401);assert.equal((await request('/bookings')).status,401);assert.equal((await request('/account/export')).status,401);});
await test('foreign origin rejected',async()=>{assert.equal((await request('/auth/login',{email:'x@example.com',password:'not-a-password'},'','POST','https://evil.example')).status,403);});
await test('minor registration rejected',async()=>{assert.equal((await request('/auth/register',{email:`minor-${suffix}@example.com`,password:'ValidPassword-test123',name:'Test Minor',dob:'2020-01-01',gender:'woman',consent:true})).status,400);});
for(const [name,gender,expected]of [['Alice','woman','active'],['Bob','man','inactive'],['Casey','self-described','pending-policy']]){
await test(`${gender} membership rule and secure registration`,async()=>{const r=await request('/auth/register',{name:'Automated Test '+name,email:`${name.toLowerCase()}-${suffix}@example.com`,password:'ValidPassword-test123',dob:'1995-01-01',gender,consent:true,companion:name==='Bob'});assert.equal(r.status,201,JSON.stringify(r.data));assert.equal(r.data.user.membership,expected);assert.equal(r.data.user.email_verified,false);assert.match(r.headers.get('set-cookie'),/Secure/);assert.match(r.headers.get('set-cookie'),/HttpOnly/);users.push({...r.data.user,cookie:r.cookie});});}
const [alice,bob,casey]=users;
await test('login wrong and correct passwords',async()=>{assert.equal((await request('/auth/login',{email:alice.email,password:'WrongPassword999'})).status,401);const r=await request('/auth/login',{email:alice.email,password:'ValidPassword-test123'});assert.equal(r.status,200);alice.cookie=r.cookie;assert.equal((await request('/auth/me',undefined,alice.cookie)).data.user.id,alice.id);});
await test('profile ownership and private saves',async()=>{const r=await request('/profile',{display_name:'Private Test Profile',city:'Mumbai',area:'Bandra',bio:'Test bio',languages:'English',interests:'Coffee',boundaries:'Public places'},alice.cookie,'PUT');assert.equal(r.status,200);assert.equal((await request('/profile',undefined,alice.cookie)).data.profile.display_name,'Private Test Profile');assert.notEqual((await request('/profile',undefined,bob.cookie)).data.profile.display_name,'Private Test Profile');assert.equal((await request('/companions')).data.companions.some(p=>p.user_id===alice.id),false);});
await test('unverified booking and real payments blocked',async()=>{assert.equal((await request('/bookings',{companion_id:bob.id},alice.cookie)).status,403);assert.equal((await request('/payments/order',{},bob.cookie)).status,503);assert.equal((await request('/payments/verify',{razorpay_signature:'forged'},bob.cookie)).status,503);assert.equal((await request('/payments/webhook',{})).status,503);});
await test('invalid verification and reset tokens rejected',async()=>{assert.equal((await request('/auth/verify',{token:'a'.repeat(64)})).status,400);assert.equal((await request('/auth/reset',{token:'b'.repeat(64),password:'AnotherStrongPassword9'})).status,400);assert.equal((await request('/auth/forgot',{email:alice.email})).status,503);});
await test('verification single-use token',async()=>{const raw=randomBytes(32).toString('hex');const hash=createHash('sha256').update(raw).digest('hex');sql(`INSERT INTO auth_tokens(token_hash,user_id,kind,expires_at) VALUES('${hash}','${alice.id}','verify',unixepoch()+600)`);assert.equal((await request('/auth/verify',{token:raw})).status,200);assert.equal((await request('/auth/verify',{token:raw})).status,400);assert.equal((await request('/auth/me',undefined,alice.cookie)).data.user.email_verified,true);});
await test('password reset revokes existing sessions and token reuse',async()=>{const raw=randomBytes(32).toString('hex'),hash=createHash('sha256').update(raw).digest('hex');sql(`INSERT INTO auth_tokens(token_hash,user_id,kind,expires_at) VALUES('${hash}','${alice.id}','reset',unixepoch()+600)`);assert.equal((await request('/auth/reset',{token:raw,password:'ChangedPassword9999'})).status,200);assert.equal((await request('/auth/me',undefined,alice.cookie)).data.user,null);assert.equal((await request('/auth/reset',{token:raw,password:'ChangedPassword9999'})).status,400);const r=await request('/auth/login',{email:alice.email,password:'ChangedPassword9999'});assert.equal(r.status,200);alice.cookie=r.cookie;});
// Privileged test-only fixtures. Never run this against a deployed database.
sql(`UPDATE users SET email_verified=1,adult_verified=1 WHERE id IN ('${alice.id}','${bob.id}','${casey.id}'); UPDATE memberships SET status='active' WHERE user_id IN ('${bob.id}','${casey.id}'); UPDATE profiles SET visible=1,companion=1,moderation_status='approved' WHERE user_id='${bob.id}'; ${Array.from({length:7},(_,i)=>`INSERT INTO availability_rules(id,user_id,weekday,start_minute,end_minute,min_notice_hours) VALUES('rule-${suffix}-${i}','${bob.id}',${i},0,1440,1);`).join('')}`);
const day=new Date(Date.now()+4*86400000).toISOString().slice(0,10),start=Math.floor(new Date(day+'T10:00:00+05:30').getTime()/1000);
const payload={companion_id:bob.id,activity:'Coffee & conversations',start_at:start,end_at:start+3600,venue:'A public café in Mumbai',introduction:'Automated test plan only.',consent:true};let first,second;
await test('past booking rejected and pending requests created',async()=>{assert.equal((await request('/bookings',{...payload,start_at:1,end_at:3601},alice.cookie)).status,400);first=await request('/bookings',payload,alice.cookie);second=await request('/bookings',payload,casey.cookie);assert.equal(first.status,201);assert.equal(second.status,201);});
await test('only companion can accept a request',async()=>{assert.equal((await request(`/bookings/${first.data.id}/status`,{status:'accepted'},alice.cookie)).status,403);});
let winner,loser;
await test('concurrent acceptance prevents double booking atomically',async()=>{const result=await Promise.all([request(`/bookings/${first.data.id}/status`,{status:'accepted'},bob.cookie),request(`/bookings/${second.data.id}/status`,{status:'accepted'},bob.cookie)]);assert.deepEqual(result.map(r=>r.status).sort(),[200,409]);winner=result[0].status===200?{id:first.data.id,user:alice}:{id:second.data.id,user:casey};loser=winner.user.id===alice.id?casey:alice;});
await test('ICS timezone and cross-user access checks',async()=>{const r=await request(`/bookings/${winner.id}/calendar.ics`,undefined,winner.user.cookie);assert.equal(r.status,200);assert.match(r.data,/DTSTART:.*T043000Z/);assert.equal((await request(`/bookings/${winner.id}/calendar.ics`,undefined,loser.cookie)).status,404);});
await test('rescheduling requires the other participant’s agreement',async()=>{const proposed=start+86400;assert.equal((await request(`/bookings/${winner.id}/reschedule`,{start_at:proposed,end_at:proposed+3600},winner.user.cookie)).status,200);assert.equal((await request(`/bookings/${winner.id}/reschedule`,{accept:true},winner.user.cookie)).status,403);assert.equal((await request(`/bookings/${winner.id}/reschedule`,{accept:true},bob.cookie)).status,200);});
let co;
await test('messages are persisted and third-party access is denied',async()=>{co=sql(`SELECT id FROM conversations WHERE booking_id='${winner.id}'`)[0].results[0].id;const r=await request(`/conversations/${co}/messages`,{body:'Test hello, public venue only.'},winner.user.cookie);assert.equal(r.status,201);assert.equal((await request(`/conversations/${co}/messages`,undefined,bob.cookie)).data.messages.length,1);assert.equal((await request(`/conversations/${co}/messages`,undefined,loser.cookie)).status,404);});
await test('reports persist and blocks stop messages and cancel bookings',async()=>{assert.equal((await request('/reports',{user_id:bob.id,reason:'Automated test report, not a genuine allegation.'},winner.user.cookie)).status,201);assert.equal((await request('/blocks',{user_id:bob.id},winner.user.cookie)).status,200);assert.equal((await request(`/conversations/${co}/messages`,{body:'This must not be sent.'},bob.cookie)).status,404);const r=await request('/bookings',undefined,winner.user.cookie);assert.equal(r.data.bookings.find(b=>b.id===winner.id).status,'cancelled');});
await test('reviews gated and admin fail closed',async()=>{assert.equal((await request('/reviews',{booking_id:winner.id,rating:5,body:'Not a completed booking'},winner.user.cookie)).status,403);assert.equal((await request('/admin/refund',{},bob.cookie)).status,503);});
await test('export excludes secrets; deletion is an explicit request',async()=>{const r=await request('/account/export',undefined,alice.cookie);assert.equal(r.status,200);assert.equal(JSON.stringify(r.data).includes('password_hash'),false);assert.equal((await request('/account/deletion',{},alice.cookie)).data.status,'pending-review');});
await test('logout removes session',async()=>{assert.equal((await request('/auth/logout',{},alice.cookie)).status,200);assert.equal((await request('/auth/me',undefined,alice.cookie)).data.user,null);});
console.log(`\n${passed} API integration tests passed.`);
}finally{if(users.length){const ids=users.map(u=>`'${u.id}'`).join(',');sql(`DELETE FROM messages WHERE sender_id IN (${ids}); DELETE FROM conversations WHERE booking_id IN (SELECT id FROM bookings WHERE requester_id IN (${ids}) OR companion_id IN (${ids})); DELETE FROM bookings WHERE requester_id IN (${ids}) OR companion_id IN (${ids}); ${['roles','profiles','consent_records','verification_records','sessions','auth_tokens','memberships','availability_rules','availability_exceptions','notifications','deletion_requests'].map(t=>`DELETE FROM ${t} WHERE user_id IN (${ids});`).join('')} DELETE FROM reports WHERE reporter_id IN (${ids}) OR reported_id IN (${ids}); DELETE FROM blocks WHERE blocker_id IN (${ids}) OR blocked_id IN (${ids}); DELETE FROM users WHERE id IN (${ids});`);}}
