import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {createHash,randomBytes} from 'node:crypto';
const base=process.env.TEST_URL||'http://localhost:3000';
if(!/^http:\/\/(localhost|127\.0\.0\.1):3000$/.test(base))throw new Error('Fixture tests run only against local preview.');
let passed=0;const users=[];const suffix=Date.now();
const sql=q=>JSON.parse(execFileSync('npx',['wrangler','d1','execute','togetherly-db','--local','--json','--command',q],{encoding:'utf8',cwd:process.cwd(),stdio:['ignore','pipe','pipe']}));
async function request(path,body,cookie='',method=body===undefined?'GET':'POST',origin=base){const r=await fetch(base+'/api'+path,{method,headers:{'Content-Type':'application/json','CF-Connecting-IP':`192.0.2.${1+suffix%254}`,Origin:origin,...(cookie?{Cookie:cookie}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}return{status:r.status,data,headers:r.headers,cookie:r.headers.get('set-cookie')?.split(';')[0]||cookie};}
const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};
try{
await test('health and launch gates',async()=>{assert.equal((await request('/health')).data.status,'ok');const config=(await request('/config')).data;assert.equal(config.payments_enabled,false);assert.equal('female_amount' in config.pricing,false);});
await test('anonymous private access denied',async()=>{assert.equal((await request('/profile')).status,401);assert.equal((await request('/bookings')).status,401);assert.equal((await request('/account/export')).status,401);for(const path of ['/notifications','/notification-preferences','/private-plans','/verification/status','/cashfree/config','/cashfree/orders'])assert.equal((await request(path)).status,401);});
await test('foreign origin rejected',async()=>{assert.equal((await request('/auth/login',{email:'x@example.com',password:'not-a-password'},'','POST','https://evil.example')).status,403);});
await test('minor registration rejected',async()=>{assert.equal((await request('/auth/register',{email:`minor-${suffix}@example.com`,password:'ValidPassword-test123',name:'Test Minor',dob:'2020-01-01',gender:'woman',consent:true})).status,400);});
for(const [name,gender,expected]of [['Alice','woman','active'],['Bob','man','inactive'],['Casey','self-described','pending-policy']]){
await test(`${gender} membership rule and secure registration`,async()=>{const r=await request('/auth/register',{name:'Automated Test '+name,email:`${name.toLowerCase()}-${suffix}@example.com`,password:'ValidPassword-test123',dob:'1995-01-01',gender,consent:true,companion:name==='Bob'});assert.equal(r.status,201,JSON.stringify(r.data));assert.equal(r.data.user.membership,expected);assert.equal(r.data.user.email_verified,false);assert.match(r.headers.get('set-cookie'),/Secure/);assert.match(r.headers.get('set-cookie'),/HttpOnly/);users.push({...r.data.user,cookie:r.cookie});});}
const [alice,bob,casey]=users;
await test('login wrong and correct passwords',async()=>{assert.equal((await request('/auth/login',{email:alice.email,password:'WrongPassword999'})).status,401);const r=await request('/auth/login',{email:alice.email,password:'ValidPassword-test123'});assert.equal(r.status,200);alice.cookie=r.cookie;assert.equal((await request('/auth/me',undefined,alice.cookie)).data.user.id,alice.id);});
await test('profile ownership and private saves',async()=>{const r=await request('/profile',{display_name:'Private Test Profile',city:'Mumbai',area:'Bandra',bio:'Test bio',languages:'English',interests:'Coffee',boundaries:'Public places'},alice.cookie,'PUT');assert.equal(r.status,200);assert.equal((await request('/profile',undefined,alice.cookie)).data.profile.display_name,'Private Test Profile');assert.notEqual((await request('/profile',undefined,bob.cookie)).data.profile.display_name,'Private Test Profile');assert.equal((await request('/companions')).data.companions.some(p=>p.user_id===alice.id),false);});
await test('unverified booking and real payments blocked',async()=>{assert.equal((await request('/bookings',{companion_id:bob.id},alice.cookie)).status,403);assert.equal((await request('/private-plans',{},alice.cookie)).status,403);assert.equal((await request('/payments/order',{},bob.cookie)).status,503);assert.equal((await request('/payments/verify',{razorpay_signature:'forged'},bob.cookie)).status,503);assert.equal((await request('/payments/webhook',{})).status,503);});
await test('invalid verification and reset tokens rejected',async()=>{assert.equal((await request('/auth/verify',{token:'a'.repeat(64)})).status,400);assert.equal((await request('/auth/reset',{token:'b'.repeat(64),password:'AnotherStrongPassword9'})).status,400);assert.equal((await request('/auth/forgot',{email:alice.email})).status,503);});
await test('verification single-use token',async()=>{const raw=randomBytes(32).toString('hex');const hash=createHash('sha256').update(raw).digest('hex');sql(`INSERT INTO auth_tokens(token_hash,user_id,kind,expires_at) VALUES('${hash}','${alice.id}','verify',unixepoch()+600)`);assert.equal((await request('/auth/verify',{token:raw})).status,200);assert.equal((await request('/auth/verify',{token:raw})).status,400);assert.equal((await request('/auth/me',undefined,alice.cookie)).data.user.email_verified,true);});
await test('password reset revokes existing sessions and token reuse',async()=>{const raw=randomBytes(32).toString('hex'),hash=createHash('sha256').update(raw).digest('hex');sql(`INSERT INTO auth_tokens(token_hash,user_id,kind,expires_at) VALUES('${hash}','${alice.id}','reset',unixepoch()+600)`);assert.equal((await request('/auth/reset',{token:raw,password:'ChangedPassword9999'})).status,200);assert.equal((await request('/auth/me',undefined,alice.cookie)).data.user,null);assert.equal((await request('/auth/reset',{token:raw,password:'ChangedPassword9999'})).status,400);const r=await request('/auth/login',{email:alice.email,password:'ChangedPassword9999'});assert.equal(r.status,200);alice.cookie=r.cookie;});
await test('private selfie requirements apply to all and ID check applies to men',async()=>{for(const u of users){const r=await request('/verification/status',undefined,u.cookie);assert.equal(r.status,200);assert.equal(r.data.requirements.selfie,true);assert.equal(r.data.requirements.id_document,u.gender==='man');assert.equal(r.data.requirements.aadhaar_optional,true);assert.equal(r.data.uploads_enabled,false);assert.equal(r.data.provider_available,false);}assert.equal((await request('/verification/start',{},bob.cookie)).status,503);assert.equal((await request('/verification/upload',{document:'fixture-only'},bob.cookie)).status,503);assert.equal((await request('/auth/me',undefined,bob.cookie)).data.user.id_document_verified,false);});
await test('Cashfree waits for new server secrets and never trusts a browser success flag',async()=>{const cfg=await request('/cashfree/config',undefined,bob.cookie);assert.equal(cfg.data.enabled,false);assert.equal(cfg.data.sandbox_only,true);assert.equal((await request('/cashfree/orders',{phone:'9999999999'},bob.cookie)).status,503);assert.equal((await request('/cashfree/webhook',{})).status,503);assert.equal((await request('/cashfree/orders/slm_test_'+('a'.repeat(32))+'/verify',{status:'paid'},bob.cookie)).status,503);assert.equal((await request('/auth/me',undefined,bob.cookie)).data.user.membership,'inactive');});
// Privileged test-only fixtures. Never run this against a deployed database.
sql(`UPDATE users SET email_verified=1,adult_verified=1,selfie_verified=1,id_document_verified=1 WHERE id IN ('${alice.id}','${bob.id}','${casey.id}'); UPDATE memberships SET status='active' WHERE user_id IN ('${bob.id}','${casey.id}'); UPDATE profiles SET visible=1,companion=1,moderation_status='approved' WHERE user_id='${bob.id}'; ${Array.from({length:7},(_,i)=>`INSERT INTO availability_rules(id,user_id,weekday,start_minute,end_minute,min_notice_hours) VALUES('rule-${suffix}-${i}','${bob.id}',${i},0,1440,1);`).join('')}`);
const day=new Date(Date.now()+4*86400000).toISOString().slice(0,10),start=Math.floor(new Date(day+'T10:00:00+05:30').getTime()/1000);

const prefs={enabled:true,city:'Mumbai',activities:['Coffee & conversations'],consent:true};
await test('notification preferences default off and require explicit opt-in',async()=>{assert.equal((await request('/notification-preferences',undefined,bob.cookie)).data.preferences.enabled,false);assert.equal((await request('/notification-preferences',{...prefs,consent:false},bob.cookie,'PUT')).status,400);assert.equal((await request('/notification-preferences',prefs,bob.cookie,'PUT')).status,200);assert.equal((await request('/notification-preferences',prefs,alice.cookie,'PUT')).status,200);assert.equal((await request('/notification-preferences',{...prefs,city:'Delhi'},casey.cookie,'PUT')).status,200);const result=await request('/notification-preferences',undefined,bob.cookie);assert.equal(result.data.preferences.enabled,true);assert.equal(result.data.channels.email,false);});
const planBody={city:'Mumbai',activity:'Coffee & conversations',start_at:start,end_at:start+3600,consent:true};let privatePlan,bobNotice;
await test('invalid private-plan time rejected',async()=>{assert.equal((await request('/private-plans',{...planBody,start_at:1,end_at:3601},alice.cookie)).status,400);});
await test('private plan creates one anonymous opt-in matching invitation',async()=>{privatePlan=await request('/private-plans',planBody,alice.cookie);assert.equal(privatePlan.status,201,JSON.stringify(privatePlan.data));assert.deepEqual(Object.keys(privatePlan.data).sort(),['id','message','status']);const inbox=await request('/notifications',undefined,bob.cookie);assert.equal(inbox.data.notifications.length,1,JSON.stringify(inbox.data));assert.equal(inbox.data.delivery,'in-app-only');bobNotice=inbox.data.notifications[0];assert.equal(bobNotice.invitation.city,'Mumbai');assert.equal(bobNotice.invitation.start_at,start);assert.equal((await request('/notifications',undefined,alice.cookie)).data.notifications.length,0);assert.equal((await request('/notifications',undefined,casey.cookie)).data.notifications.length,0);for(const value of [alice.name,alice.email,alice.id,bob.email,bob.id,'owner_id','recipient_id','photo','image_key']){if(value==='photo')continue;assert.equal(JSON.stringify(inbox.data).includes(value),false,`Leaked ${value}`);}assert.equal((await request('/private-plans',undefined,bob.cookie)).data.plans.length,0);});
await test('notification read and invitation actions enforce ownership',async()=>{assert.equal((await request('/notifications/'+bobNotice.id+'/read',{},casey.cookie)).status,404);assert.equal((await request('/private-invitations/'+bobNotice.invitation.id+'/respond',{response:'interested'},casey.cookie)).status,404);assert.equal((await request('/private-plans/'+privatePlan.data.id+'/cancel',{},bob.cookie)).status,404);assert.equal((await request('/notifications/'+bobNotice.id+'/read',{},bob.cookie)).status,200);assert.equal((await request('/notifications',undefined,bob.cookie)).data.unread,0);});
await test('concurrent interest replies are single-use and notify sender once',async()=>{const replies=await Promise.all([request('/private-invitations/'+bobNotice.invitation.id+'/respond',{response:'interested'},bob.cookie),request('/private-invitations/'+bobNotice.invitation.id+'/respond',{response:'interested'},bob.cookie)]);assert.deepEqual(replies.map(r=>r.status).sort(),[200,404]);const inbox=await request('/notifications',undefined,alice.cookie);assert.equal(inbox.data.notifications.length,1);assert.equal(inbox.data.notifications[0].kind,'private_reply');assert.equal(JSON.stringify(inbox.data).includes(bob.id),false);assert.equal(JSON.stringify(inbox.data).includes(bob.name),false);});
await test('revoked eligibility immediately hides invitations and replies',async()=>{sql(`UPDATE users SET adult_verified=0 WHERE id='${bob.id}'`);assert.equal((await request('/notifications',undefined,bob.cookie)).data.notifications.length,0);assert.equal((await request('/notifications',undefined,alice.cookie)).data.notifications.length,0);sql(`UPDATE users SET adult_verified=1 WHERE id='${bob.id}'`);});
await test('missing selfie or male ID verification blocks matching and hides invitations',async()=>{sql(`UPDATE users SET selfie_verified=0 WHERE id='${alice.id}'`);assert.equal((await request('/private-plans',planBody,alice.cookie)).status,403);assert.equal((await request('/notifications',undefined,bob.cookie)).data.notifications.length,0);sql(`UPDATE users SET selfie_verified=1 WHERE id='${alice.id}'; UPDATE users SET id_document_verified=0 WHERE id='${bob.id}'`);assert.equal((await request('/private-plans',planBody,bob.cookie)).status,403);assert.equal((await request('/notifications',undefined,alice.cookie)).data.notifications.length,0);sql(`UPDATE users SET id_document_verified=1 WHERE id='${bob.id}'`);});
await test('opt-out prevents new notifications without revealing member counts',async()=>{assert.equal((await request('/notification-preferences',{...prefs,enabled:false,consent:false},bob.cookie,'PUT')).status,200);const before=(await request('/notifications',undefined,bob.cookie)).data.notifications.length;const r=await request('/private-plans',{...planBody,start_at:start+3600,end_at:start+7200},alice.cookie);assert.equal(r.status,201);assert.equal((await request('/notifications',undefined,bob.cookie)).data.notifications.length,before);assert.equal('matches' in r.data,false);await request('/notification-preferences',prefs,bob.cookie,'PUT');});
let declinedPlan;
await test('declines do not notify or reveal the recipient',async()=>{declinedPlan=await request('/private-plans',{...planBody,start_at:start+7200,end_at:start+10800},alice.cookie);assert.equal(declinedPlan.status,201);const notices=(await request('/notifications',undefined,bob.cookie)).data.notifications;const n=notices.find(n=>n.invitation.start_at===start+7200);assert.ok(n);assert.equal((await request('/private-invitations/'+n.invitation.id+'/respond',{response:'declined'},bob.cookie)).status,200);assert.equal((await request('/notifications',undefined,alice.cookie)).data.notifications.length,1);});
await test('cancelled interests disappear from both private inboxes',async()=>{assert.equal((await request('/private-plans/'+declinedPlan.data.id+'/cancel',{},alice.cookie)).status,200);assert.equal((await request('/notifications',undefined,bob.cookie)).data.notifications.some(n=>n.invitation.start_at===start+7200),false);});
await test('blocking via anonymous invitation hides both sides and prevents new matches',async()=>{assert.equal((await request('/private-invitations/'+bobNotice.invitation.id+'/block',{},casey.cookie)).status,404);assert.equal((await request('/private-invitations/'+bobNotice.invitation.id+'/block',{},bob.cookie)).status,200);assert.equal((await request('/notifications',undefined,bob.cookie)).data.notifications.length,0);assert.equal((await request('/notifications',undefined,alice.cookie)).data.notifications.length,0);const r=await request('/private-plans',{...planBody,start_at:start+10800,end_at:start+14400},alice.cookie);assert.equal(r.status,201);assert.equal((await request('/notifications',undefined,bob.cookie)).data.notifications.length,0);});
// Remove only fixture blocks so independent legacy-booking tests can run.
sql(`DELETE FROM blocks WHERE blocker_id='${bob.id}' AND blocked_id='${alice.id}'`);
const payload={companion_id:bob.id,activity:'Coffee & conversations',start_at:start,end_at:start+3600,venue:'A public café in Mumbai',introduction:'Automated test plan only.',consent:true};let first,second;
await test('public directory and new direct bookings closed; legacy fixtures remain operable',async()=>{assert.deepEqual((await request('/companions')).data.companions,[]);assert.deepEqual((await request('/companions',undefined,alice.cookie)).data.companions,[]);assert.equal((await request('/bookings',payload,alice.cookie)).status,410);first={data:{id:'legacy-first-'+suffix}};second={data:{id:'legacy-second-'+suffix}};for(const [bid,owner]of [[first.data.id,alice.id],[second.data.id,casey.id]])sql(`INSERT INTO bookings(id,requester_id,companion_id,activity,start_at,end_at,venue,introduction,status,expires_at) VALUES('${bid}','${owner}','${bob.id}','Coffee',${start},${start+3600},'Public café','Test only','pending',${start-3600})`);});
await test('only companion can accept a request',async()=>{assert.equal((await request(`/bookings/${first.data.id}/status`,{status:'accepted'},alice.cookie)).status,403);});
let winner,loser;
await test('concurrent acceptance prevents double booking atomically',async()=>{const result=await Promise.all([request(`/bookings/${first.data.id}/status`,{status:'accepted'},bob.cookie),request(`/bookings/${second.data.id}/status`,{status:'accepted'},bob.cookie)]);assert.deepEqual(result.map(r=>r.status).sort(),[200,409]);winner=result[0].status===200?{id:first.data.id,user:alice}:{id:second.data.id,user:casey};loser=winner.user.id===alice.id?casey:alice;});
await test('ICS timezone and cross-user access checks',async()=>{const r=await request(`/bookings/${winner.id}/calendar.ics`,undefined,winner.user.cookie);assert.equal(r.status,200);assert.match(r.data,/DTSTART:.*T043000Z/);assert.equal((await request(`/bookings/${winner.id}/calendar.ics`,undefined,loser.cookie)).status,404);});
await test('rescheduling requires the other participant’s agreement',async()=>{const proposed=start+86400;assert.equal((await request(`/bookings/${winner.id}/reschedule`,{start_at:proposed,end_at:proposed+3600},winner.user.cookie)).status,200);assert.equal((await request(`/bookings/${winner.id}/reschedule`,{accept:true},winner.user.cookie)).status,403);assert.equal((await request(`/bookings/${winner.id}/reschedule`,{accept:true},bob.cookie)).status,200);});
let co;
await test('messages are persisted and third-party access is denied',async()=>{co=sql(`SELECT id FROM conversations WHERE booking_id='${winner.id}'`)[0].results[0].id;const r=await request(`/conversations/${co}/messages`,{body:'Test hello, public venue only.'},winner.user.cookie);assert.equal(r.status,201);assert.equal((await request(`/conversations/${co}/messages`,undefined,bob.cookie)).data.messages.length,1);assert.equal((await request(`/conversations/${co}/messages`,undefined,loser.cookie)).status,404);});
await test('reports persist and blocks stop messages and cancel bookings',async()=>{assert.equal((await request('/reports',{user_id:bob.id,reason:'Automated test report, not a genuine allegation.'},winner.user.cookie)).status,201);assert.equal((await request('/blocks',{user_id:bob.id},winner.user.cookie)).status,200);assert.equal((await request(`/conversations/${co}/messages`,{body:'This must not be sent.'},bob.cookie)).status,404);const r=await request('/bookings',undefined,winner.user.cookie);assert.equal(r.data.bookings.find(b=>b.id===winner.id).status,'cancelled');});
await test('reviews gated and admin fail closed',async()=>{assert.equal((await request('/reviews',{booking_id:winner.id,rating:5,body:'Not a completed booking'},winner.user.cookie)).status,403);assert.equal((await request('/admin/refund',{},bob.cookie)).status,503);});
await test('export excludes secrets; deletion is an explicit request',async()=>{const r=await request('/account/export',undefined,alice.cookie);assert.equal(r.status,200);assert.equal(JSON.stringify(r.data).includes('password_hash'),false);assert.equal((await request('/account/deletion',{},alice.cookie)).data.status,'pending-review');assert.equal((await request('/notification-preferences',undefined,alice.cookie)).data.preferences.enabled,false);assert.equal((await request('/private-plans',undefined,alice.cookie)).data.plans.every(p=>p.status==='cancelled'),true);assert.equal((await request('/notifications',undefined,bob.cookie)).data.notifications.length,0);});
await test('logout removes session',async()=>{assert.equal((await request('/auth/logout',{},alice.cookie)).status,200);assert.equal((await request('/auth/me',undefined,alice.cookie)).data.user,null);});
console.log(`\n${passed} API integration tests passed.`);
}finally{if(users.length){const ids=users.map(u=>`'${u.id}'`).join(',');sql(`DELETE FROM notifications WHERE user_id IN (${ids}) OR invitation_id IN (SELECT id FROM private_invitations WHERE recipient_id IN (${ids}) OR plan_id IN (SELECT id FROM private_plans WHERE owner_id IN (${ids}))); DELETE FROM private_invitations WHERE recipient_id IN (${ids}) OR plan_id IN (SELECT id FROM private_plans WHERE owner_id IN (${ids})); DELETE FROM private_plans WHERE owner_id IN (${ids}); DELETE FROM notification_preferences WHERE user_id IN (${ids}); DELETE FROM messages WHERE sender_id IN (${ids}); DELETE FROM conversations WHERE booking_id IN (SELECT id FROM bookings WHERE requester_id IN (${ids}) OR companion_id IN (${ids})); DELETE FROM bookings WHERE requester_id IN (${ids}) OR companion_id IN (${ids}); ${['roles','profiles','consent_records','verification_records','sessions','auth_tokens','memberships','availability_rules','availability_exceptions','notifications','deletion_requests'].map(t=>`DELETE FROM ${t} WHERE user_id IN (${ids});`).join('')} DELETE FROM reports WHERE reporter_id IN (${ids}) OR reported_id IN (${ids}); DELETE FROM blocks WHERE blocker_id IN (${ids}) OR blocked_id IN (${ids}); DELETE FROM users WHERE id IN (${ids});`);}}
