import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
const base='http://localhost:3000';
const sql=q=>JSON.parse(execFileSync('npx',['wrangler','d1','execute','togetherly-db','--local','--json','--command',q],{encoding:'utf8',stdio:['ignore','pipe','pipe']}));
await mkdir('tests/artifacts',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
let checks=0;
try{for(const [name,width,height]of [['desktop',1440,1000],['mobile',390,844]]){
 const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:1});const page=await context.newPage();const errors=[];const ids=[];page.on('pageerror',e=>errors.push(e.message));
 try{
 await page.goto(base,{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:`tests/artifacts/home-${name}.png`,fullPage:true});
 assert.equal(await page.locator('h1').innerText(),'Good company.\nMeaningful\nmoments.');assert.match(await page.title(),/Saathlumi/);assert.doesNotMatch(await page.locator('body').innerText(),/togetherly/i);checks++;
 assert.equal(await page.locator('img,.profile-card').count(),0);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks++;
 await page.locator('#discovery-search [name=city]').selectOption('Mumbai');await page.locator('#discovery-search button').click();await expect(page.locator('#private-plan-form')).toBeVisible();assert.equal(await page.locator('#private-plan-form [name=city]').inputValue(),'Mumbai');assert.equal(await page.locator('img,.profile-card').count(),0);checks++;
 const tomorrow=new Date(Date.now()+3*86400000).toISOString().slice(0,10);
 await page.locator('#private-plan-form [name=activity]').selectOption('Coffee & conversations');await page.locator('[name=date]').fill(tomorrow);await page.locator('[name=time]').fill('14:00');await page.locator('[name=consent]').check();await page.locator('#private-plan-form button').click();await expect(page).toHaveURL(base+'/login');checks++;
 for(const path of ['/companions/ananya','/companions/arjun','/companions/meera','/static/images/sample-ananya.jpg','/static/images/community.jpg']){const response=await context.request.get(base+path);assert.equal(response.status(),404,path);}checks++;
 await page.goto(base+'/notifications',{waitUntil:'networkidle'});assert.match(await page.locator('main').innerText(),/log in/i);assert.equal(await page.locator('#notification-list').count(),0);checks++;
 await page.goto(base+'/pricing',{waitUntil:'networkidle'});assert.match(await page.locator('.pricing-grid').innerText(),/₹299/);assert.doesNotMatch(await page.locator('.pricing-grid').innerText(),/FOR WOMEN|\bFree\b|Join for free/i);checks++;
 await page.goto(base+'/register',{waitUntil:'networkidle'});assert.equal(await page.locator('img').count(),0);assert.equal(await page.locator('input[name=password]').getAttribute('minlength'),'12');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks++;
 // Real local test account and D1 preferences, not mocked responses.
 const response=await context.request.post(base+'/api/auth/register',{headers:{Origin:base,'CF-Connecting-IP':`192.0.2.${name==='desktop'?233:234}`},data:{name:'Private Browser Test',email:`browser-${randomUUID()}@example.test`,password:'UniqueBrowserTestPassword99',dob:'1995-01-01',gender:'woman',consent:true}});assert.equal(response.status(),201,await response.text());const u=(await response.json()).user;ids.push(u.id);
 await page.goto(base+'/verification',{waitUntil:'networkidle'});await expect(page.locator('#verification-status')).toContainText('Verification pending');assert.match(await page.locator('main').innerText(),/Selfie & liveness verification/);assert.equal(await page.locator('.verification-step button:disabled').count(),1);assert.equal(await page.locator('input[type=file]').count(),0);assert.equal(await page.locator('img').count(),0);checks++;
 await page.goto(base+'/notifications',{waitUntil:'networkidle'});await expect(page.locator('#notification-preferences-form')).toBeVisible();assert.equal(await page.locator('[name=enabled]').isChecked(),false);assert.match(await page.locator('#notification-list').innerText(),/No private invitations yet/);checks++;
 await page.locator('#notification-preferences-form [name=city]').selectOption('Mumbai');await page.locator('[name=activities][value="Coffee & conversations"]').check();await page.locator('[name=enabled]').check();await page.locator('#notification-preferences-form button').click();await expect(page.locator('#form-feedback')).toContainText('Preferences saved');await page.reload({waitUntil:'networkidle'});await expect(page.locator('[name=enabled]')).toBeChecked();await expect(page.locator('[name=activities][value="Coffee & conversations"]')).toBeChecked();checks++;
 const sender=randomUUID(),plan=randomUUID(),start=Math.floor(Date.now()/1000)+172800;ids.push(sender);
 sql(`UPDATE users SET email_verified=1,adult_verified=1,selfie_verified=1,id_document_verified=1 WHERE id='${u.id}'; INSERT INTO users(id,email,name,password_hash,dob,gender,email_verified,adult_verified,selfie_verified,id_document_verified) VALUES('${sender}','${sender}@example.test','Hidden Sender Test','test-only','1995-01-01','woman',1,1,1,1); INSERT INTO memberships(user_id,status,source) VALUES('${sender}','active','free'); INSERT INTO private_plans(id,owner_id,city,activity,start_at,end_at) VALUES('${plan}','${sender}','Mumbai','Coffee & conversations',${start},${start+3600});`);
 await page.locator('[data-action=refresh-notifications]').click();await expect(page.locator('.private-notification')).toHaveCount(1);assert.match(await page.locator('#notification-list').innerText(),/Someone would like to meet/);assert.doesNotMatch(await page.locator('#notification-list').innerText(),/Hidden Sender Test|@example.test/);assert.equal(await page.locator('img').count(),0);checks++;
 await page.locator('[data-read-notification]').click();await expect(page.locator('.unread-dot')).toHaveCount(0);checks++;
 await page.locator('[data-response=interested]').click();await expect(page.locator('.response-status')).toContainText('Interest shared privately');assert.equal(sql(`SELECT count(*) AS n FROM notifications WHERE user_id='${sender}' AND kind='private_reply'`)[0].results[0].n,1);checks++;
 await page.screenshot({path:`tests/artifacts/notifications-${name}.png`,fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${name} notifications overflow`);checks++;
 await page.locator('[data-private-block]').click();await page.locator('[data-confirm-private=block]').click();await expect(page.locator('.private-notification')).toHaveCount(0);checks++;
 await page.locator('[name=enabled]').uncheck();await page.locator('#notification-preferences-form button').click();await expect(page.locator('#form-feedback')).toContainText('paused');checks++;
 await page.goto(base+'/browse',{waitUntil:'networkidle'});await page.locator('#private-plan-form [name=city]').selectOption('Mumbai');await page.locator('#private-plan-form [name=activity]').selectOption('Movies');await page.locator('[name=date]').fill(tomorrow);await page.locator('[name=time]').fill('14:00');await page.locator('[name=consent]').check();await page.locator('#private-plan-form button').click();await expect(page.locator('#form-feedback')).toContainText('private interest is saved');await expect(page.locator('.own-private-plan')).toHaveCount(1);checks++;
 await page.locator('[data-cancel-plan]').click();await page.locator('[data-confirm-private=cancel]').click();await expect(page.locator('.plan-state')).toContainText('cancelled');checks++;
 await page.goto(base+'/calendar',{waitUntil:'networkidle'});await page.locator('[data-view=week]').click();assert.ok(await page.locator('[data-date]:visible').count()<=7);await page.locator('[data-view=day]').click();assert.equal(await page.locator('[data-date]:visible').count(),1);checks++;
 if(name==='mobile'){await page.locator('[data-action=menu]').click();await page.locator('.mobile-nav a[href="/safety"]').click();assert.match(await page.locator('h1').innerText(),/Real boundaries/);checks++;}
 await page.goto(base+'/#faq',{waitUntil:'networkidle'});await page.locator('details').first().locator('summary').click();assert.equal(await page.locator('details').first().getAttribute('open'),'');assert.doesNotMatch(await page.locator('body').innerText(),/women.{0,40}free|for women|join for free/i);assert.equal(await page.locator('img').count(),0);checks++;
 sql(`UPDATE users SET gender='man',id_document_verified=0,selfie_verified=0 WHERE id='${u.id}'`);
 await page.goto(base+'/verification',{waitUntil:'networkidle'});await expect(page.locator('#verification-document-type')).toBeVisible();assert.match(await page.locator('main').innerText(),/Masked Aadhaar or alternative ID/);assert.equal(await page.locator('input[type=file]').isDisabled(),true);await page.locator('#verification-document-type').selectOption('alternative');assert.equal(await page.locator('input[type=file]').isDisabled(),true);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks++;
 await page.goto(base+'/checkout',{waitUntil:'networkidle'});await expect(page.locator('#cashfree-availability')).not.toContainText('Checking');assert.match(await page.locator('.checkout-card').innerText(),/SANDBOX ONLY/);assert.equal(await page.locator('#cashfree-pay').isDisabled(),true);assert.equal(await page.locator('[name=phone]').isDisabled(),true);assert.equal(await page.locator('script[src*=cashfree]').count(),0);checks++;
 await page.goto(base+'/payment-result?status=success',{waitUntil:'networkidle'});await expect(page.locator('#cashfree-result')).toContainText('No valid test order reference');assert.doesNotMatch(await page.locator('#cashfree-result').innerText(),/payment confirmed/i);checks++;
 assert.deepEqual(errors,[],`${name} script errors`);checks++;
 console.log(`PASS ${name} photo-free navigation, private plans, real notification inbox, preferences, interest, blocking and cancellation.`);
 }finally{if(ids.length){const values=ids.map(id=>`'${id}'`).join(',');sql(`DELETE FROM notifications WHERE user_id IN (${values}) OR invitation_id IN(SELECT id FROM private_invitations WHERE recipient_id IN(${values}) OR plan_id IN(SELECT id FROM private_plans WHERE owner_id IN(${values}))); DELETE FROM private_invitations WHERE recipient_id IN(${values}) OR plan_id IN(SELECT id FROM private_plans WHERE owner_id IN(${values})); DELETE FROM private_plans WHERE owner_id IN(${values}); DELETE FROM blocks WHERE blocker_id IN(${values}) OR blocked_id IN(${values}); ${['notification_preferences','auth_tokens','sessions','consent_records','profiles','roles','memberships'].map(t=>`DELETE FROM ${t} WHERE user_id IN(${values});`).join('')} DELETE FROM users WHERE id IN(${values});`);}await context.close();}
}console.log(`${checks} browser checks passed. Screenshots in tests/artifacts.`);}finally{await browser.close();}
