import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { readdirSync,readFileSync } from 'node:fs';
import { Hono } from 'hono';
import { HTTPException } from 'hono/http-exception';
import { mountCashfree,cashfreeReadiness,cashfreeSignature,cashfreeSnapshot } from '../src/cashfree.js';

const fakeEnv={CASHFREE_APP_ID:'test-fixture-app-id-not-a-real-key',CASHFREE_SECRET_KEY:'test-fixture-secret-not-a-real-key',CASHFREE_ENV:'sandbox',CASHFREE_SANDBOX_ENABLED:'true',APP_ORIGIN:'https://app.example.test'};
function fixtureDB(){const sqlite=new DatabaseSync(':memory:');for(const name of readdirSync('migrations').filter(n=>n.endsWith('.sql')).sort())sqlite.exec(readFileSync('migrations/'+name,'utf8'));for(const [id,gender,status]of [['member-one','man','inactive'],['member-two','man','inactive'],['member-woman','woman','active']]){sqlite.prepare("INSERT INTO users(id,email,name,password_hash,dob,gender) VALUES(?,?,?,'fixture','1990-01-01',?)").run(id,id+'@example.test',id,gender);sqlite.prepare("INSERT INTO memberships(user_id,status,source) VALUES(?,?,'pending')").run(id,status);}function prepare(sql){let params=[];const q={bind(...p){params=p;return q;},async first(){return sqlite.prepare(sql).get(...params)||null;},async all(){return {results:sqlite.prepare(sql).all(...params)};},async run(){const r=sqlite.prepare(sql).run(...params);return{meta:{changes:Number(r.changes)}};}};return q;}return{sqlite,prepare,async batch(queries){sqlite.exec('BEGIN');try{const results=[];for(const q of queries)results.push(await q.run());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};}
function appFixture(db){const app=new Hono();mountCashfree(app,{auth:async(c,next)=>{const id=c.req.header('x-test-user');const user=db.sqlite.prepare('SELECT * FROM users WHERE id=?').get(id||'');if(!user)return c.json({error:'Please log in'},401);c.set('user',user);await next();},limit:async()=>{}});app.onError((e,c)=>c.json({error:e.message},e instanceof HTTPException?e.status:500));return app;}

test('Cashfree configuration fails closed for missing keys and production environment',()=>{assert.equal(cashfreeReadiness({}).enabled,false);assert.equal(cashfreeReadiness({...fakeEnv,CASHFREE_SECRET_KEY:''}).enabled,false);assert.equal(cashfreeReadiness({...fakeEnv,CASHFREE_ENV:'production'}).enabled,false);assert.equal(cashfreeReadiness({...fakeEnv,APP_ORIGIN:'http://example.test'}).enabled,false);assert.equal(cashfreeReadiness(fakeEnv).enabled,true);});
test('Cashfree signature uses Base64 HMAC of timestamp plus exact raw body',async()=>{const timestamp='1760000000000',raw='{"type":"PAYMENT_SUCCESS_WEBHOOK"}';const expected=createHmac('sha256','fixture-secret').update(timestamp+raw).digest('base64');assert.equal(await cashfreeSignature('fixture-secret',timestamp,raw),expected);assert.notEqual(await cashfreeSignature('fixture-secret',timestamp,raw+' '),expected);});
test('Cashfree validates exact order, customer, amount and currency; capture required',()=>{const local={id:'order',user_id:'member',amount:29900,currency:'INR',status:'active'};const order={order_id:'order',customer_details:{customer_id:'member'},order_amount:299,order_currency:'INR',order_status:'PAID'};const payment={order_id:'order',payment_amount:299,payment_currency:'INR',payment_status:'SUCCESS',is_captured:true,cf_payment_id:'1'};assert.equal(cashfreeSnapshot(local,order,[payment]).status,'paid');assert.equal(cashfreeSnapshot(local,order,[{...payment,is_captured:false}]).status,'active');assert.equal(cashfreeSnapshot(local,order,[{...payment,payment_status:'FAILED'}]).status,'active');for(const change of [{order_amount:2.99},{order_currency:'USD'},{order_id:'other'},{customer_details:{customer_id:'another'}}])assert.throws(()=>cashfreeSnapshot(local,{...order,...change},[payment]));assert.equal(cashfreeSnapshot({...local,status:'paid'},{...order,order_status:'ACTIVE'},[]).status,'paid');assert.equal(cashfreeSnapshot(local,order,[payment],'REFUND_STATUS_WEBHOOK').status,'review');assert.equal(cashfreeSnapshot({...local,status:'review'},order,[payment]).status,'review');});

test('Cashfree route integration with mocked provider and actual SQLite persistence',async t=>{
 const db=fixtureDB(),app=appFixture(db),orders=new Map(),attempts=new Map(),seenHeaders=[];const original=globalThis.fetch;let postCount=0;
 globalThis.fetch=async(url,options={})=>{assert.ok(String(url).startsWith('https://sandbox.cashfree.com/pg/'));assert.equal(options.headers['x-client-id'],fakeEnv.CASHFREE_APP_ID);assert.equal(options.headers['x-client-secret'],fakeEnv.CASHFREE_SECRET_KEY);assert.equal(options.headers['x-api-version'],'2025-01-01');const path=String(url).split('/pg/')[1];if(options.method==='POST'){postCount++;const b=JSON.parse(options.body);seenHeaders.push(options.headers['x-idempotency-key']);assert.equal(b.order_amount,299);assert.equal(b.order_currency,'INR');assert.equal(b.customer_details.customer_id,'member-one');assert.equal('customer_name' in b.customer_details,false);assert.equal('customer_email' in b.customer_details,false);assert.match(b.order_meta.return_url,/^https:\/\/app\.example\.test\/payment-result\?order_id=/);const order=orders.get(b.order_id)||{...b,order_status:'ACTIVE',payment_session_id:'session_fixture_'+b.order_id};orders.set(b.order_id,order);return Response.json(order);}const id=path.split('/')[1];if(path.endsWith('/payments'))return Response.json(attempts.get(id)||[]);if(!orders.has(id))return Response.json({message:'not found'},{status:404});return Response.json(orders.get(id));};
 async function call(path,data,user='member-one',headers={}){const response=await app.request('https://app.example.test'+path,{method:data===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(user?{'x-test-user':user}:{}),...headers},...(data!==undefined?{body:typeof data==='string'?data:JSON.stringify(data)}:{})},{...fakeEnv,DB:db});return{status:response.status,data:await response.json()};}
 try{
 await t.test('anonymous checkout denied; configuration never returns secrets',async()=>{assert.equal((await call('/cashfree/config',undefined,null)).status,401);const r=await call('/cashfree/config');assert.equal(r.status,200);assert.equal(r.data.enabled,true);assert.equal(JSON.stringify(r.data).includes(fakeEnv.CASHFREE_SECRET_KEY),false);});
 await t.test('paid plan and phone validation',async()=>{assert.equal((await call('/cashfree/orders',{phone:'9999999999'},'member-woman')).status,409);assert.equal((await call('/cashfree/orders',{phone:'12'})).status,400);});
 let created;
 await t.test('parallel create calls reuse canonical order and provider idempotency key',async()=>{const [a,b]=await Promise.all([call('/cashfree/orders',{phone:'9999999999',amount:1}),call('/cashfree/orders',{phone:'9999999999',amount:1})]);assert.equal(a.status,200,JSON.stringify(a));assert.equal(b.status,200,JSON.stringify(b));assert.equal(a.data.order_id,b.data.order_id);assert.equal(a.data.amount,29900);assert.equal(a.data.environment,'sandbox');assert.equal(db.sqlite.prepare('SELECT count(*) AS n FROM cashfree_orders').get().n,1);assert.equal(new Set(seenHeaders).size,1);created=a.data;});
 await t.test('browser callbacks cannot create success; foreign account cannot inspect',async()=>{assert.equal((await call('/cashfree/orders/'+created.order_id+'/verify',{},'member-two')).status,404);const r=await call('/cashfree/orders/'+created.order_id+'/verify',{status:'SUCCESS'});assert.equal(r.data.status,'active');assert.equal(r.data.membership_activated,false);});
 await t.test('verified provider capture confirms test payment without real membership',async()=>{orders.get(created.order_id).order_status='PAID';attempts.set(created.order_id,[{order_id:created.order_id,cf_payment_id:'fixture-pay-1',payment_amount:299,payment_currency:'INR',payment_status:'SUCCESS',is_captured:true}]);const r=await call('/cashfree/orders/'+created.order_id+'/verify',{});assert.equal(r.data.status,'paid');assert.equal(r.data.membership_activated,false);assert.equal(db.sqlite.prepare("SELECT status FROM memberships WHERE user_id='member-one'").get().status,'inactive');assert.equal(db.sqlite.prepare("SELECT adult_verified,selfie_verified,id_document_verified FROM users WHERE id='member-one'").get().selfie_verified,0);});
 const ts=String(Date.now()),raw=JSON.stringify({type:'PAYMENT_SUCCESS_WEBHOOK',data:{order:{order_id:created.order_id}}});
 await t.test('invalid webhook signatures rejected before processing',async()=>{assert.equal((await call('/cashfree/webhook',raw,null,{'x-webhook-timestamp':ts,'x-webhook-signature':'forged'})).status,400);const signature=await cashfreeSignature(fakeEnv.CASHFREE_SECRET_KEY,ts,raw);assert.equal((await call('/cashfree/webhook',raw+' ',null,{'x-webhook-timestamp':ts,'x-webhook-signature':signature})).status,400);});
 await t.test('signed webhook deduplicates and excludes private payment payload',async()=>{const headers={'x-webhook-timestamp':ts,'x-webhook-signature':await cashfreeSignature(fakeEnv.CASHFREE_SECRET_KEY,ts,raw)};assert.equal((await call('/cashfree/webhook',raw,null,headers)).status,200);assert.equal((await call('/cashfree/webhook',raw,null,headers)).data.duplicate,true);assert.equal(db.sqlite.prepare('SELECT count(*) AS n FROM cashfree_events').get().n,1);});
 await t.test('refund event is terminal review, including after old capture replay',async()=>{const payload=JSON.stringify({type:'REFUND_STATUS_WEBHOOK',data:{refund:{order_id:created.order_id}}});const headers={'x-webhook-timestamp':ts,'x-webhook-signature':await cashfreeSignature(fakeEnv.CASHFREE_SECRET_KEY,ts,payload)};assert.equal((await call('/cashfree/webhook',payload,null,headers)).data.status,'review');assert.equal((await call('/cashfree/orders/'+created.order_id+'/verify',{})).data.status,'review');});
 await t.test('history excludes session IDs and provider credentials',async()=>{const r=await call('/cashfree/orders');assert.equal(r.data.orders.length,1);const json=JSON.stringify(r.data);assert.equal(json.includes('payment_session_id'),false);assert.equal(json.includes(fakeEnv.CASHFREE_SECRET_KEY),false);assert.equal((await call('/cashfree/orders',undefined,'member-two')).data.orders.length,0);});
 }finally{globalThis.fetch=original;db.sqlite.close();}
});
