import { Hono } from 'hono'
import { getCookie, setCookie, deleteCookie } from 'hono/cookie'
import { HTTPException } from 'hono/http-exception'
import { bodyLimit } from 'hono/body-limit'
import { nextPaymentState, paymentMatchesOrder, signPayment as hmac, signaturesEqual as equal } from './payment-state.js'

type Env = { DB: any; APP_ORIGIN?: string; EMAIL_API_KEY?: string; EMAIL_FROM?: string; RAZORPAY_KEY_ID?: string; RAZORPAY_KEY_SECRET?: string; RAZORPAY_WEBHOOK_SECRET?: string; PAYMENTS_ENABLED?: string }
export const api = new Hono<{ Bindings: Env; Variables: { user: any } }>()
const now = () => Math.floor(Date.now() / 1000)
const id = () => crypto.randomUUID()
const bytes = (s: string) => new TextEncoder().encode(s)
const hex = (b: ArrayBuffer | Uint8Array) => Array.from(new Uint8Array(b)).map(x => x.toString(16).padStart(2, '0')).join('')
const sha = async (s: string) => hex(await crypto.subtle.digest('SHA-256', bytes(s)))
const token = () => hex(crypto.getRandomValues(new Uint8Array(32)))
const fail = (status: number, message: string): never => { throw new HTTPException(status as any, { message }) }
function str(v: unknown, min: number, max: number, field: string) { if (typeof v !== 'string' || v.trim().length < min || v.length > max) fail(400, `Please enter a valid ${field}.`); return (v as string).trim() }
function emailValue(v: unknown) { const email = str(v, 3, 254, 'email address').toLowerCase(); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) fail(400, 'Please enter a valid email address.'); return email }
function ageEligible(dob: string) { if (!/^\d{4}-\d{2}-\d{2}$/.test(dob)) return false; const d = new Date(dob + 'T00:00:00Z'); if (!Number.isFinite(+d) || d.toISOString().slice(0, 10) !== dob) return false; const cutoff = new Date(); cutoff.setUTCFullYear(cutoff.getUTCFullYear() - 18); return d <= cutoff && d.getUTCFullYear() > 1900 }
async function passwordHash(password: string, salt = token()) { const key = await crypto.subtle.importKey('raw', bytes(password), 'PBKDF2', false, ['deriveBits']); const result = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt: bytes(salt), iterations: 100000, hash: 'SHA-256' }, key, 256); return `pbkdf2:100000:${salt}:${hex(result)}` }
async function validPassword(password: string, stored: string) { return equal(await passwordHash(password, stored.split(':')[2]), stored) }
async function limit(c: any, bucket: string, max = 15, seconds = 900) { const ip = c.req.header('cf-connecting-ip') || 'local-preview'; const key = await sha(bucket + ':' + ip); const time = now(); const row = await c.env.DB.prepare('INSERT INTO rate_limits(key,count,reset_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN reset_at<=? THEN 1 ELSE count+1 END, reset_at=CASE WHEN reset_at<=? THEN excluded.reset_at ELSE reset_at END RETURNING count').bind(key, time + seconds, time, time).first(); if (row.count > max) fail(429, 'A few too many attempts. Please try again later.'); }
async function currentUser(c: any) { const cookie = getCookie(c, '__Host-togetherly'); if (!cookie) return null; return c.env.DB.prepare('SELECT u.*,m.status AS membership FROM sessions s JOIN users u ON u.id=s.user_id LEFT JOIN memberships m ON m.user_id=u.id WHERE s.token_hash=? AND s.expires_at>? AND u.suspended=0').bind(await sha(cookie), now()).first() }
function safeUser(u: any, env: Env) { return u ? { id: u.id, name: u.name, email: u.email, gender: u.gender, email_verified: !!u.email_verified, adult_verified: !!u.adult_verified, membership: u.membership, email_delivery: !!(env.EMAIL_API_KEY && env.EMAIL_FROM && env.APP_ORIGIN) } : null }
async function auth(c: any, next: any) { const u = await currentUser(c); if (!u) fail(401, 'Please log in to continue.'); c.set('user', u); await next() }
async function eligible(c: any) { const u = c.get('user'); if (!u.email_verified) fail(403, 'Please verify your email first.'); if (!u.adult_verified) fail(403, 'Adult verification is required. This service is not configured yet.'); if (u.membership !== 'active') fail(403, 'An active membership is required.'); return u }
async function session(c: any, userId: string) { const value = token(); await c.env.DB.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').bind(await sha(value), userId, now() + 86400 * 7).run(); setCookie(c, '__Host-togetherly', value, { httpOnly: true, secure: true, sameSite: 'Lax', path: '/', maxAge: 604800 }); }
async function sendToken(c: any, user: any, kind: 'verify' | 'reset') { if (!c.env.EMAIL_API_KEY || !c.env.EMAIL_FROM || !c.env.APP_ORIGIN) return false; const value = token(); const hash = await sha(value); await c.env.DB.prepare('INSERT INTO auth_tokens(token_hash,user_id,kind,expires_at) VALUES(?,?,?,?)').bind(hash, user.id, kind, now() + (kind === 'reset' ? 1800 : 86400)).run(); const url = `${c.env.APP_ORIGIN}/${kind === 'reset' ? 'reset-password' : 'verify-email'}?token=${value}`; try { const res = await fetch('https://api.resend.com/emails', { method: 'POST', headers: { Authorization: `Bearer ${c.env.EMAIL_API_KEY}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ from: c.env.EMAIL_FROM, to: user.email, subject: kind === 'reset' ? 'Reset your Saathlumi password' : 'Your first hello: verify your Saathlumi email', text: `Use this secure link to ${kind === 'reset' ? 'reset your password' : 'verify your email'}: ${url}\n\nIf you did not request this, ignore this message. Saathlumi is for adults 18+ and strictly platonic activities.` }) }); if (!res.ok) throw new Error('email'); return true } catch { await c.env.DB.prepare('DELETE FROM auth_tokens WHERE token_hash=?').bind(hash).run(); return false } }
async function blocked(db: any, a: string, b: string) { return !!await db.prepare('SELECT 1 FROM blocks WHERE (blocker_id=? AND blocked_id=?) OR (blocker_id=? AND blocked_id=?)').bind(a, b, b, a).first() }
async function settings(db: any) { const { results } = await db.prepare('SELECT key,value FROM settings').all(); return Object.fromEntries(results.map((r: any) => [r.key, r.value])) }

api.use('*', bodyLimit({ maxSize: 65536, onError: c => c.json({ error: 'Request body is too large.' }, 413) }))
api.use('*', async (c, next) => { c.header('Cache-Control', 'no-store'); if (!c.env.DB) fail(503, 'Database is not configured. Please try again after setup.'); if (!['GET', 'HEAD', 'OPTIONS'].includes(c.req.method) && c.req.path !== '/api/payments/webhook') { const origin = c.req.header('origin'); const allowed = new Set([new URL(c.req.url).origin, c.env.APP_ORIGIN].filter(Boolean)); if (!origin || !allowed.has(origin)) fail(403, 'Request origin is not permitted.'); const length = Number(c.req.header('content-length') || '0'); if (length > 16384) fail(413, 'Request is too large.'); } await next() })
api.get('/health', async c => { await c.env.DB.prepare('SELECT 1').first(); return c.json({ status: 'ok', mode: 'preview', payments: 'disabled-until-approved', verification: 'not-configured' }) })
api.get('/config', async c => { const s = await settings(c.env.DB); return c.json({ mode: 'preview', pricing: { male_amount: Number(s.male_amount), currency: 'INR', kind: 'one-time', tax_configured: s.tax_configured === 'true', other_gender_policy: 'pending' }, payments_enabled: false, adult_verification_enabled: false }) })
api.get('/auth/me', async c => c.json({ user: safeUser(await currentUser(c), c.env) }))
api.post('/auth/register', async c => {
 await limit(c, 'register', 8, 3600); const b = await c.req.json(); const email = emailValue(b.email); const name = str(b.name, 2, 60, 'name'); const password = str(b.password, 12, 128, 'password of at least 12 characters'); const gender = str(b.gender, 3, 30, 'gender'); if (!['woman', 'man', 'self-described', 'prefer-not-to-say'].includes(gender)) fail(400, 'Choose a supported gender option.'); if (!ageEligible(b.dob)) fail(400, 'Saathlumi is only for adults aged 18 and above.'); if (b.consent !== true) fail(400, 'Please accept the policies to continue.'); const exists = await c.env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first(); if (exists) fail(409, 'This email already has an account. Please log in or reset your password.'); const uid = id(), hash = await passwordHash(password); const membership = gender === 'woman' ? 'active' : gender === 'man' ? 'inactive' : 'pending-policy';
 await c.env.DB.batch([
 c.env.DB.prepare('INSERT INTO users(id,email,name,password_hash,dob,gender) VALUES(?,?,?,?,?,?)').bind(uid, email, name, hash, b.dob, gender),
 c.env.DB.prepare("INSERT INTO roles(user_id,role) VALUES(?,'member')").bind(uid),
 c.env.DB.prepare('INSERT INTO profiles(user_id,display_name,companion) VALUES(?,?,?)').bind(uid, name, b.companion ? 1 : 0),
 c.env.DB.prepare('INSERT INTO memberships(user_id,status,source) VALUES(?,?,?)').bind(uid, membership, gender === 'woman' ? 'free' : 'pending'),
 ...['terms', 'privacy', 'guidelines'].map(policy => c.env.DB.prepare('INSERT INTO consent_records(id,user_id,policy,version) VALUES(?,?,?,?)').bind(id(), uid, policy, '2026-09-draft')),
 ...(b.companion ? [c.env.DB.prepare("INSERT INTO roles(user_id,role) VALUES(?,'companion')").bind(uid)] : [])]);
 await session(c, uid); const emailSent = await sendToken(c, { id: uid, email }, 'verify'); const u = await currentUser(c) || { id: uid, name, email, gender, membership }; return c.json({ user: safeUser(u, c.env), message: emailSent ? 'Your account is ready. Check your inbox to verify your email.' : 'Account created. Email delivery is not configured; booking remains locked until verification is available.' }, 201)
})
api.post('/auth/login', async c => { await limit(c, 'login', 15); const b = await c.req.json(); const email = emailValue(b.email); const password = str(b.password, 1, 128, 'password'); await limit(c, 'account:' + await sha(email), 10); const u = await c.env.DB.prepare('SELECT u.*,m.status AS membership FROM users u LEFT JOIN memberships m ON m.user_id=u.id WHERE u.email=?').bind(email).first(); const dummy = 'pbkdf2:100000:0000000000000000000000000000000000000000000000000000000000000000:0000000000000000000000000000000000000000000000000000000000000000'; if (!await validPassword(password, u?.password_hash || dummy) || !u || u.suspended) fail(401, 'Email or password is incorrect.'); await session(c, u.id); return c.json({ user: safeUser(u, c.env) }) })
api.post('/auth/logout', async c => { const value = getCookie(c, '__Host-togetherly'); if (value) await c.env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha(value)).run(); deleteCookie(c, '__Host-togetherly', { path: '/', secure: true }); return c.json({ success: true }) })
api.post('/auth/resend', auth, async c => { await limit(c, 'resend', 3, 3600); const u = c.get('user'); if (u.email_verified) return c.json({ message: 'Your email is already confirmed.' }); if (!await sendToken(c, u, 'verify')) fail(503, 'Email delivery is not configured or temporarily unavailable.'); return c.json({ message: 'A verification link is on its way.' }) })
api.post('/auth/verify', async c => { await limit(c, 'verify', 12); const b = await c.req.json(); const t = await sha(str(b.token, 64, 64, 'verification token')); const result = await c.env.DB.prepare("UPDATE auth_tokens SET used=1 WHERE token_hash=? AND kind='verify' AND used=0 AND expires_at>? RETURNING user_id").bind(t, now()).first(); if (!result) fail(400, 'This verification link is invalid, expired, or already used.'); await c.env.DB.prepare('UPDATE users SET email_verified=1 WHERE id=?').bind(result.user_id).run(); return c.json({ success: true }) })
api.post('/auth/forgot', async c => { await limit(c, 'forgot', 4, 3600); const b = await c.req.json(); const email = emailValue(b.email); if (!c.env.EMAIL_API_KEY || !c.env.EMAIL_FROM || !c.env.APP_ORIGIN) fail(503, 'Password reset emails are unavailable until the email provider is configured.'); const u = await c.env.DB.prepare('SELECT id,email FROM users WHERE email=?').bind(email).first(); if (u) await sendToken(c, u, 'reset'); return c.json({ message: 'If that account exists, a password reset link has been requested. Check your inbox.' }) })
api.post('/auth/reset', async c => { await limit(c, 'reset', 10); const b = await c.req.json(); const t = await sha(str(b.token, 64, 64, 'reset token')); const hash = await passwordHash(str(b.password, 12, 128, 'password of at least 12 characters')); const result = await c.env.DB.batch([c.env.DB.prepare("UPDATE users SET password_hash=? WHERE id=(SELECT user_id FROM auth_tokens WHERE token_hash=? AND kind='reset' AND used=0 AND expires_at>?)").bind(hash, t, now()), c.env.DB.prepare("DELETE FROM sessions WHERE user_id=(SELECT user_id FROM auth_tokens WHERE token_hash=? AND kind='reset' AND used=0 AND expires_at>?)").bind(t, now()), c.env.DB.prepare("UPDATE auth_tokens SET used=1 WHERE token_hash=? AND kind='reset' AND used=0 AND expires_at>?").bind(t, now())]); if (!result[0].meta.changes) fail(400, 'This reset link is invalid, expired, or already used.'); return c.json({ success: true }) })
api.get('/profile', auth, async c => c.json({ profile: await c.env.DB.prepare('SELECT display_name,city,area,bio,languages,interests,boundaries,companion,visible,moderation_status FROM profiles WHERE user_id=?').bind(c.get('user').id).first() }))
api.put('/profile', auth, async c => { const b = await c.req.json(); const name = str(b.display_name, 2, 60, 'display name'); const city = str(b.city, 2, 80, 'city'); const fields = ['area', 'bio', 'languages', 'interests', 'boundaries'].map((key, i) => str(b[key] || '', 0, [80, 1000, 150, 250, 600][i], key)); await c.env.DB.batch([c.env.DB.prepare("UPDATE profiles SET display_name=?,city=?,area=?,bio=?,languages=?,interests=?,boundaries=?,companion=?,visible=0,moderation_status='pending',updated_at=? WHERE user_id=?").bind(name, city, ...fields, b.companion ? 1 : 0, now(), c.get('user').id), c.env.DB.prepare('UPDATE users SET name=? WHERE id=?').bind(name, c.get('user').id), ...(b.companion ? [c.env.DB.prepare("INSERT OR IGNORE INTO roles(user_id,role) VALUES(?,'companion')").bind(c.get('user').id)] : [])]); return c.json({ success: true, visibility: 'private' }) })
api.get('/companions', c => c.json({ companions: [], mode: 'private', message: 'Member profiles are not public. Use private meeting interests and in-app notifications.' }))
api.get('/bookings', auth, async c => { const uid = c.get('user').id; await c.env.DB.prepare("UPDATE bookings SET status='expired',updated_at=? WHERE status='pending' AND expires_at<=? AND (requester_id=? OR companion_id=?)").bind(now(), now(), uid, uid).run(); const { results } = await c.env.DB.prepare('SELECT id,requester_id,companion_id,activity,start_at,end_at,venue,status,proposed_start_at,proposed_end_at FROM bookings WHERE requester_id=? OR companion_id=? ORDER BY start_at DESC LIMIT 100').bind(uid, uid).all(); return c.json({ bookings: results }) })
async function validateSlot(db: any, companionId: string, start: number, end: number) { if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start < now() + 3600 || ![3600, 5400, 7200].includes(end - start)) fail(400, 'Choose a future time and a duration of 60, 90, or 120 minutes.'); const local = new Date((start + 19800) * 1000); const localEnd = new Date((end + 19800) * 1000); const day = local.toISOString().slice(0, 10); if (day !== localEnd.toISOString().slice(0, 10)) fail(400, 'Meetings must begin and end on the same local day.'); const startMinute = local.getUTCHours() * 60 + local.getUTCMinutes(), endMinute = localEnd.getUTCHours() * 60 + localEnd.getUTCMinutes(); const rule = await db.prepare('SELECT 1 FROM availability_rules WHERE user_id=? AND weekday=? AND start_minute<=? AND end_minute>=? AND ? >= ? + min_notice_hours*3600').bind(companionId, local.getUTCDay(), startMinute, endMinute, start, now()).first(); const exception = await db.prepare('SELECT 1 FROM availability_exceptions WHERE user_id=? AND day=? AND blocked=1').bind(companionId, day).first(); if (!rule || exception) fail(409, 'That time is outside the companion’s published availability.'); }
api.post('/bookings', auth, async c => { await eligible(c); return c.json({ error: 'Direct member browsing and new direct bookings are closed. Use a private meeting interest instead.' }, 410) })
api.post('/bookings/:id/status', auth, async c => { const u = c.get('user'); const b = await c.req.json(); const row = await c.env.DB.prepare('SELECT * FROM bookings WHERE id=? AND (requester_id=? OR companion_id=?)').bind(c.req.param('id'), u.id, u.id).first(); if (!row) fail(404, 'Booking not found.'); const next = b.status; const transitions: Record<string, string[]> = { pending: ['accepted', 'declined', 'cancelled'], accepted: ['cancelled', 'completed', 'no-show'] }; if (!transitions[row.status]?.includes(next)) fail(409, 'This booking cannot move to that state.'); if (['accepted', 'declined'].includes(next) && row.companion_id !== u.id) fail(403, 'Only the companion can accept or decline.'); if (next === 'accepted') { await eligible(c); if (await blocked(c.env.DB, row.requester_id, row.companion_id)) fail(403, 'This interaction is unavailable.'); if (row.expires_at <= now()) fail(409, 'This request has expired.'); const requester = await c.env.DB.prepare("SELECT 1 FROM users u JOIN memberships m ON m.user_id=u.id WHERE u.id=? AND u.email_verified=1 AND u.adult_verified=1 AND u.suspended=0 AND m.status='active'").bind(row.requester_id).first(); if (!requester) fail(409, 'The requesting member is no longer eligible.'); await validateSlot(c.env.DB, row.companion_id, row.start_at, row.end_at); }
 if (['completed', 'no-show'].includes(next) && now() < row.end_at) fail(409, 'The meeting has not ended yet.'); const result = await c.env.DB.prepare('UPDATE bookings SET status=?,updated_at=? WHERE id=? AND status=?').bind(next, now(), row.id, row.status).run(); if (!result.meta.changes) fail(409, 'Booking changed. Please refresh.'); if (next === 'accepted') await c.env.DB.prepare('INSERT OR IGNORE INTO conversations(id,booking_id) VALUES(?,?)').bind(id(), row.id).run(); return c.json({ success: true, status: next }) })
api.post('/bookings/:id/reschedule', auth, async c => { const u = await eligible(c); const b = await c.req.json(); const row = await c.env.DB.prepare("SELECT * FROM bookings WHERE id=? AND status='accepted' AND (requester_id=? OR companion_id=?)").bind(c.req.param('id'), u.id, u.id).first(); if (!row) fail(404, 'Accepted booking not found.'); if (await blocked(c.env.DB, row.requester_id, row.companion_id)) fail(403, 'This interaction is unavailable.'); if (b.accept === true) { if (!row.proposed_start_at || row.proposed_by === u.id) fail(403, 'Only the other participant can accept a proposal.'); await validateSlot(c.env.DB, row.companion_id, row.proposed_start_at, row.proposed_end_at); const r = await c.env.DB.prepare("UPDATE bookings SET start_at=proposed_start_at,end_at=proposed_end_at,proposed_start_at=NULL,proposed_end_at=NULL,proposed_by=NULL,updated_at=? WHERE id=? AND status='accepted' AND proposed_start_at=? AND proposed_end_at=? AND proposed_by=?").bind(now(), row.id, row.proposed_start_at, row.proposed_end_at, row.proposed_by).run(); if (!r.meta.changes) fail(409, 'The proposal changed. Refresh and try again.'); } else { const start = Number(b.start_at), end = Number(b.end_at); await validateSlot(c.env.DB, row.companion_id, start, end); await c.env.DB.prepare("UPDATE bookings SET proposed_start_at=?,proposed_end_at=?,proposed_by=?,updated_at=? WHERE id=? AND status='accepted'").bind(start, end, u.id, now(), row.id).run(); } return c.json({ success: true }) })
api.get('/bookings/:id/calendar.ics', auth, async c => { const uid = c.get('user').id; const row = await c.env.DB.prepare("SELECT * FROM bookings WHERE id=? AND status='accepted' AND (requester_id=? OR companion_id=?)").bind(c.req.param('id'), uid, uid).first(); if (!row) fail(404, 'Accepted booking not found.'); const date = (n: number) => new Date(n * 1000).toISOString().replace(/[-:]/g, '').replace(/\.\d{3}/, ''); const escape = (s: string) => s.replace(/\\/g, '\\\\').replace(/\r?\n/g, '\\n').replace(/,/g, '\\,').replace(/;/g, '\\;'); c.header('Content-Type', 'text/calendar; charset=utf-8'); c.header('Content-Disposition', 'attachment; filename="saathlumi-meeting.ics"'); return c.body(`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Saathlumi//Platonic Meetings//EN\r\nBEGIN:VEVENT\r\nUID:${row.id}@togetherly\r\nDTSTAMP:${date(now())}\r\nDTSTART:${date(row.start_at)}\r\nDTEND:${date(row.end_at)}\r\nSUMMARY:${escape(row.activity)} with Saathlumi\r\nLOCATION:${escape(row.venue)}\r\nDESCRIPTION:Meet in public. Respect boundaries. Consent can be withdrawn.\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`) })
async function conversation(c: any) { const u = await eligible(c); const row = await c.env.DB.prepare("SELECT co.id,b.requester_id,b.companion_id FROM conversations co JOIN bookings b ON b.id=co.booking_id WHERE co.id=? AND b.status IN ('accepted','completed') AND (b.requester_id=? OR b.companion_id=?)").bind(c.req.param('id'), u.id, u.id).first(); if (!row || await blocked(c.env.DB, row.requester_id, row.companion_id)) fail(404, 'Conversation unavailable.'); return row }
api.get('/conversations/:id/messages', auth, async c => { const co = await conversation(c); const { results } = await c.env.DB.prepare('SELECT id,sender_id,body,created_at FROM messages WHERE conversation_id=? ORDER BY created_at DESC LIMIT 100').bind(co.id).all(); return c.json({ messages: results.reverse() }) })
api.post('/conversations/:id/messages', auth, async c => { const co = await conversation(c); await limit(c, 'messages:' + c.get('user').id, 30, 60); const b = await c.req.json(); const msgId = id(); await c.env.DB.prepare('INSERT INTO messages(id,conversation_id,sender_id,body) VALUES(?,?,?,?)').bind(msgId, co.id, c.get('user').id, str(b.body, 1, 2000, 'message')).run(); return c.json({ id: msgId }, 201) })
api.post('/blocks', auth, async c => { const b = await c.req.json(), uid = c.get('user').id; const other = str(b.user_id, 1, 60, 'member'); if (other === uid) fail(400, 'You cannot block yourself.'); if (!await c.env.DB.prepare('SELECT id FROM users WHERE id=?').bind(other).first()) fail(404, 'Member not found.'); await c.env.DB.batch([c.env.DB.prepare('INSERT OR IGNORE INTO blocks(blocker_id,blocked_id) VALUES(?,?)').bind(uid, other), c.env.DB.prepare("UPDATE bookings SET status='cancelled',updated_at=? WHERE status IN ('pending','accepted') AND ((requester_id=? AND companion_id=?) OR (requester_id=? AND companion_id=?))").bind(now(), uid, other, other, uid)]); return c.json({ success: true }) })
api.post('/reports', auth, async c => { await limit(c, 'reports:' + c.get('user').id, 10, 3600); const b = await c.req.json(); const reported = str(b.user_id, 1, 60, 'member'); if (!await c.env.DB.prepare('SELECT id FROM users WHERE id=?').bind(reported).first()) fail(404, 'Member not found.'); await c.env.DB.prepare('INSERT INTO reports(id,reporter_id,reported_id,reason) VALUES(?,?,?,?)').bind(id(), c.get('user').id, reported, str(b.reason, 10, 1500, 'reason')).run(); return c.json({ success: true, message: 'Report recorded. This preview has no staffed moderation service or promised response time.' }, 201) })
api.post('/reviews', auth, async c => { const u = c.get('user'), b = await c.req.json(); const row = await c.env.DB.prepare("SELECT 1 FROM bookings WHERE id=? AND status='completed' AND (requester_id=? OR companion_id=?)").bind(str(b.booking_id, 1, 60, 'booking'), u.id, u.id).first(); if (!row) fail(403, 'Only participants of completed bookings can leave reviews.'); const rating = Number(b.rating); if (!Number.isInteger(rating) || rating < 1 || rating > 5) fail(400, 'Choose a rating from 1 to 5.'); await c.env.DB.prepare('INSERT INTO reviews(id,booking_id,author_id,rating,body) VALUES(?,?,?,?,?)').bind(id(), b.booking_id, u.id, rating, str(b.body, 5, 1000, 'review')).run(); return c.json({ success: true, status: 'pending-moderation' }, 201) })
api.get('/account/export', auth, async c => { const u = c.get('user'); const uid = u.id; const queries = ['SELECT display_name,city,area,bio,languages,interests,boundaries FROM profiles WHERE user_id=?', 'SELECT policy,version,accepted_at FROM consent_records WHERE user_id=?', 'SELECT status,source,payment_id FROM memberships WHERE user_id=?', 'SELECT id,amount,currency,status,created_at FROM payment_orders WHERE user_id=?']; const data = await c.env.DB.batch(queries.map(q => c.env.DB.prepare(q).bind(uid))); const bookings = await c.env.DB.prepare('SELECT id,activity,start_at,end_at,venue,introduction,status FROM bookings WHERE requester_id=? OR companion_id=?').bind(uid, uid).all(); const messages = await c.env.DB.prepare('SELECT id,conversation_id,body,created_at FROM messages WHERE sender_id=?').bind(uid).all(); const reports = await c.env.DB.prepare('SELECT id,reason,status,created_at FROM reports WHERE reporter_id=?').bind(uid).all(); return c.json({ account: { ...safeUser(u, c.env), dob: u.dob, created_at: u.created_at }, profile: data[0].results, consent: data[1].results, membership: data[2].results, orders: data[3].results, bookings: bookings.results, sent_messages: messages.results, reports: reports.results, notification_preferences: (await c.env.DB.prepare('SELECT enabled,city,activities,consent_version,updated_at FROM notification_preferences WHERE user_id=?').bind(uid).all()).results, private_plans: (await c.env.DB.prepare('SELECT id,city,activity,start_at,end_at,status,created_at FROM private_plans WHERE owner_id=?').bind(uid).all()).results, notifications: (await c.env.DB.prepare('SELECT id,kind,body,created_at,read_at FROM notifications WHERE user_id=?').bind(uid).all()).results }) })
api.post('/account/deletion', auth, async c => { const uid = c.get('user').id; await c.env.DB.batch([c.env.DB.prepare('INSERT OR IGNORE INTO deletion_requests(user_id) VALUES(?)').bind(uid), c.env.DB.prepare('UPDATE profiles SET visible=0 WHERE user_id=?').bind(uid), c.env.DB.prepare('UPDATE notification_preferences SET enabled=0 WHERE user_id=?').bind(uid), c.env.DB.prepare("UPDATE private_plans SET status='cancelled' WHERE owner_id=?").bind(uid)]); return c.json({ success: true, status: 'pending-review' }) })

const privateCities = ['Bengaluru', 'Mumbai', 'Delhi', 'Pune', 'Hyderabad']
const privateActivities = ['Coffee & conversations', 'Food & dining', 'Movies', 'City exploring', 'Events & music']
api.get('/notification-preferences', auth, async c => {
 const row = await c.env.DB.prepare('SELECT enabled,city,activities FROM notification_preferences WHERE user_id=?').bind(c.get('user').id).first()
 return c.json({ preferences: row ? { enabled: !!row.enabled, city: row.city, activities: JSON.parse(row.activities) } : { enabled: false, city: '', activities: [] }, channels: { in_app: true, email: false, push: false } })
})
api.put('/notification-preferences', auth, async c => {
 const u = c.get('user'), b = await c.req.json()
 if (typeof b.enabled !== 'boolean' || !privateCities.includes(b.city) || !Array.isArray(b.activities) || !b.activities.length || b.activities.length > 5 || b.activities.some((a: unknown) => !privateActivities.includes(a as string))) fail(400, 'Choose a supported city and at least one activity.')
 if (b.enabled && b.consent !== true) fail(400, 'Please opt in to private in-app invitations.')
 if (await c.env.DB.prepare('SELECT 1 FROM deletion_requests WHERE user_id=?').bind(u.id).first()) fail(403, 'Matching is unavailable while account deletion is pending.')
 await c.env.DB.prepare("INSERT INTO notification_preferences(user_id,enabled,city,activities) VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET enabled=excluded.enabled,city=excluded.city,activities=excluded.activities,updated_at=unixepoch(),consent_version='private-notifications-v1'").bind(u.id, b.enabled ? 1 : 0, b.city, JSON.stringify([...new Set(b.activities)])).run()
 return c.json({ success: true, message: b.enabled ? 'Preferences saved. Private invitations are delivered in-app once your email, adult verification, and membership are eligible.' : 'New private invitation notifications are paused.' })
})
api.post('/private-plans', auth, async c => {
 const u = await eligible(c), b = await c.req.json()
 await limit(c, 'private-plan:' + u.id, 5, 3600)
 if (await c.env.DB.prepare('SELECT 1 FROM deletion_requests WHERE user_id=?').bind(u.id).first()) fail(403, 'Matching is unavailable while account deletion is pending.')
 if (!privateCities.includes(b.city) || !privateActivities.includes(b.activity) || b.consent !== true) fail(400, 'Choose a city and activity and confirm your consent.')
 const start = Number(b.start_at), end = Number(b.end_at)
 if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start < now() + 3600 || start > now() + 90 * 86400 || ![3600, 5400, 7200].includes(end - start)) fail(400, 'Choose a time at least one hour ahead, within 90 days, for 60, 90, or 120 minutes.')
 const planId = id()
 await c.env.DB.prepare('INSERT INTO private_plans(id,owner_id,city,activity,start_at,end_at) VALUES(?,?,?,?,?,?)').bind(planId, u.id, b.city, b.activity, start, end).run()
 // Do not reveal matching member counts, identities, or who opted out.
 return c.json({ id: planId, status: 'open', message: 'Your private interest is saved. Matching opted-in, eligible members receive an in-app invitation. This does not guarantee a match or confirm a meeting.' }, 201)
})
api.get('/private-plans', auth, async c => {
 const { results } = await c.env.DB.prepare("SELECT id,city,activity,start_at,end_at,CASE WHEN status='open' AND start_at<=? THEN 'expired' ELSE status END AS status,created_at FROM private_plans WHERE owner_id=? ORDER BY created_at DESC LIMIT 50").bind(now(), c.get('user').id).all()
 return c.json({ plans: results })
})
api.post('/private-plans/:id/cancel', auth, async c => {
 const r = await c.env.DB.prepare("UPDATE private_plans SET status='cancelled' WHERE id=? AND owner_id=? AND status='open'").bind(c.req.param('id'), c.get('user').id).run()
 if (!r.meta.changes) fail(404, 'An open plan was not found.')
 return c.json({ success: true })
})
api.get('/notifications', auth, async c => {
 const uid = c.get('user').id
 const { results } = await c.env.DB.prepare(`SELECT n.id,n.kind,n.body,n.read_at,n.created_at,i.id AS invitation_id,i.state,p.city,p.activity,p.start_at,p.end_at,
 CASE WHEN p.owner_id=? THEN 'owner' ELSE 'recipient' END AS invitation_role
 FROM notifications n LEFT JOIN private_invitations i ON i.id=n.invitation_id LEFT JOIN private_plans p ON p.id=i.plan_id
 LEFT JOIN users owner ON owner.id=p.owner_id LEFT JOIN users recipient ON recipient.id=i.recipient_id
 LEFT JOIN memberships om ON om.user_id=owner.id LEFT JOIN memberships rm ON rm.user_id=recipient.id
 WHERE n.user_id=? AND (n.invitation_id IS NULL OR (
 p.status='open' AND p.start_at>? AND (p.owner_id=? OR i.recipient_id=?)
 AND owner.suspended=0 AND recipient.suspended=0 AND owner.email_verified=1 AND recipient.email_verified=1
 AND owner.adult_verified=1 AND recipient.adult_verified=1 AND om.status='active' AND rm.status='active'
 AND NOT EXISTS(SELECT 1 FROM deletion_requests WHERE user_id IN (p.owner_id,i.recipient_id))
 AND NOT EXISTS(SELECT 1 FROM blocks WHERE (blocker_id=p.owner_id AND blocked_id=i.recipient_id) OR (blocker_id=i.recipient_id AND blocked_id=p.owner_id))))
 ORDER BY n.created_at DESC,n.id DESC LIMIT 50`).bind(uid, uid, now(), uid, uid).all()
 const notifications = results.map((n: any) => ({ id: n.id, kind: n.kind, body: n.body, read_at: n.read_at, created_at: n.created_at, invitation: n.invitation_id ? { id: n.invitation_id, role: n.invitation_role, state: n.state, city: n.city, activity: n.activity, start_at: n.start_at, end_at: n.end_at } : null }))
 return c.json({ notifications, unread: notifications.filter((n: any) => !n.read_at).length, delivery: 'in-app-only' })
})
api.post('/notifications/:id/read', auth, async c => {
 const r = await c.env.DB.prepare('UPDATE notifications SET read_at=COALESCE(read_at,?) WHERE id=? AND user_id=?').bind(now(), c.req.param('id'), c.get('user').id).run()
 if (!r.meta.changes) fail(404, 'Notification not found.')
 return c.json({ success: true })
})
api.post('/private-invitations/:id/respond', auth, async c => {
 const u = await eligible(c), b = await c.req.json()
 await limit(c, 'private-response:' + u.id, 30, 3600)
 if (!['interested','declined'].includes(b.response)) fail(400, 'Choose interested or decline.')
 const r = await c.env.DB.prepare(`UPDATE private_invitations SET state=?,responded_at=?
 WHERE id=? AND recipient_id=? AND state='pending' AND EXISTS(
 SELECT 1 FROM private_plans p JOIN users owner ON owner.id=p.owner_id JOIN memberships om ON om.user_id=owner.id
 JOIN users recipient ON recipient.id=private_invitations.recipient_id JOIN memberships rm ON rm.user_id=recipient.id
 WHERE p.id=private_invitations.plan_id AND p.status='open' AND p.start_at>?
 AND owner.email_verified=1 AND owner.adult_verified=1 AND owner.suspended=0 AND om.status='active'
 AND recipient.email_verified=1 AND recipient.adult_verified=1 AND recipient.suspended=0 AND rm.status='active'
 AND NOT EXISTS(SELECT 1 FROM deletion_requests WHERE user_id IN (owner.id,recipient.id))
 AND NOT EXISTS(SELECT 1 FROM blocks WHERE (blocker_id=owner.id AND blocked_id=recipient.id) OR (blocker_id=recipient.id AND blocked_id=owner.id)))`).bind(b.response, now(), c.req.param('id'), u.id, now()).run()
 if (!r.meta.changes) fail(404, 'This invitation is unavailable or has already been answered.')
 return c.json({ success: true, message: b.response === 'interested' ? 'Your interest was shared privately. No name, photo, or contact details were disclosed. This is not a confirmed meeting.' : 'Invitation declined. No decline notification is sent to the other member.' })
})
api.post('/private-invitations/:id/block', auth, async c => {
 const uid = c.get('user').id
 const row = await c.env.DB.prepare('SELECT p.owner_id,i.recipient_id FROM private_invitations i JOIN private_plans p ON p.id=i.plan_id WHERE i.id=? AND (i.recipient_id=? OR p.owner_id=?)').bind(c.req.param('id'), uid, uid).first()
 if (!row) fail(404, 'Invitation not found.')
 const other = row.owner_id === uid ? row.recipient_id : row.owner_id
 await c.env.DB.prepare('INSERT OR IGNORE INTO blocks(blocker_id,blocked_id) VALUES(?,?)').bind(uid, other).run()
 return c.json({ success: true, message: 'This member is blocked. Their invitations will no longer appear.' })
})

async function razor(env: Env, path: string, method = 'GET', body?: any) { const response = await fetch(`https://api.razorpay.com/v1/${path}`, { method, headers: { Authorization: 'Basic ' + btoa(env.RAZORPAY_KEY_ID + ':' + env.RAZORPAY_KEY_SECRET), 'Content-Type': 'application/json' }, ...(body ? { body: JSON.stringify(body) } : {}) }); if (!response.ok) fail(502, 'The payment provider could not complete this request.'); return response.json() as Promise<any> }
async function paymentReady(c: any) { const s = await settings(c.env.DB); if (c.env.PAYMENTS_ENABLED !== 'true' || !c.env.RAZORPAY_KEY_ID || !c.env.RAZORPAY_KEY_SECRET || !c.env.RAZORPAY_WEBHOOK_SECRET || s.tax_configured !== 'true' || s.pricing_approved !== 'true') fail(503, 'Payments are disabled pending merchant approval, credentials, tax configuration, and legal review.'); return s }
api.post('/payments/order', auth, async c => { const s = await paymentReady(c); const u = c.get('user'); if (!u.email_verified) fail(403, 'Please verify your email first.'); if (u.gender !== 'man') fail(409, 'This paid plan does not apply to your account.'); if (u.membership === 'active') fail(409, 'Your membership is already active.'); if (u.membership === 'revoked') fail(409, 'Your payment history requires manual review before a new purchase.'); await limit(c, 'payment:' + u.id, 5, 3600); const existing = await c.env.DB.prepare("SELECT id,amount,currency FROM payment_orders WHERE user_id=? AND status='created'").bind(u.id).first(); if (existing) return c.json({ order: existing, key_id: c.env.RAZORPAY_KEY_ID }); const amount = Number(s.male_amount); if (!Number.isSafeInteger(amount) || amount !== 29900) fail(503, 'The approved membership amount must be reviewed before checkout.'); const order = await razor(c.env, 'orders', 'POST', { amount, currency: 'INR', receipt: id(), notes: { user_id: u.id, purpose: 'one-time membership' } }); await c.env.DB.prepare("INSERT INTO payment_orders(id,user_id,amount,currency,status) VALUES(?,?,?,?,'created')").bind(order.id, u.id, amount, 'INR').run(); return c.json({ order: { id: order.id, amount, currency: 'INR' }, key_id: c.env.RAZORPAY_KEY_ID }) })
async function reconcilePayment(c: any, payment: any, eventId: string, eventType: string, expectedUser?: string) { const order = await c.env.DB.prepare('SELECT * FROM payment_orders WHERE id=?').bind(payment.order_id).first(); if (!paymentMatchesOrder(order, payment, expectedUser)) fail(400, 'Payment details do not match an issued order.'); const refunded = Number(payment.amount_refunded || 0); const status = nextPaymentState(order.status, payment, eventType); const exists = await c.env.DB.prepare('SELECT 1 FROM webhook_events WHERE id=?').bind(eventId).first(); if (exists) return { duplicate: true, status: order.status };
 const statements = [c.env.DB.prepare('INSERT OR IGNORE INTO webhook_events(id,event_type) VALUES(?,?)').bind(eventId, eventType), c.env.DB.prepare("UPDATE payment_orders SET status=CASE WHEN status='disputed' OR ?='disputed' THEN 'disputed' WHEN status='refunded' OR ?='refunded' THEN 'refunded' WHEN status='captured' OR ?='captured' THEN 'captured' ELSE ? END WHERE id=?").bind(status, status, status, status, order.id), c.env.DB.prepare('INSERT INTO payments(id,order_id,user_id,amount,currency,status,refunded_amount) VALUES(?,?,?,?,?,(SELECT status FROM payment_orders WHERE id=?),?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,refunded_amount=MAX(payments.refunded_amount,excluded.refunded_amount),updated_at=unixepoch()').bind(payment.id, order.id, order.user_id, order.amount, order.currency, order.id, refunded)];
 if (status === 'captured') statements.push(c.env.DB.prepare("UPDATE memberships SET status='active',source='payment',payment_id=?,updated_at=? WHERE user_id=? AND status<>'revoked' AND EXISTS(SELECT 1 FROM payment_orders WHERE id=? AND status='captured')").bind(payment.id, now(), order.user_id, order.id)); if (['refunded', 'disputed'].includes(status)) statements.push(c.env.DB.prepare("UPDATE memberships SET status='revoked',source='payment',payment_id=?,updated_at=? WHERE user_id=?").bind(payment.id, now(), order.user_id)); await c.env.DB.batch(statements); const updated = await c.env.DB.prepare('SELECT status FROM payment_orders WHERE id=?').bind(order.id).first(); return { status: updated.status }
}
api.post('/payments/verify', auth, async c => { await paymentReady(c); await limit(c, 'payment-verify:' + c.get('user').id, 15); const b = await c.req.json(); const orderId = str(b.razorpay_order_id, 6, 80, 'order ID'), paymentId = str(b.razorpay_payment_id, 6, 80, 'payment ID'); if (!/^[a-zA-Z0-9_]+$/.test(paymentId) || !/^[a-zA-Z0-9_]+$/.test(orderId)) fail(400, 'Invalid payment identifiers.'); const signature = await hmac(c.env.RAZORPAY_KEY_SECRET!, orderId + '|' + paymentId); if (!equal(signature, String(b.razorpay_signature || ''))) fail(400, 'Payment signature could not be verified.'); const payment = await razor(c.env, 'payments/' + paymentId); if (payment.order_id !== orderId) fail(400, 'Payment order mismatch.'); const result = await reconcilePayment(c, payment, `checkout:${payment.id}:${payment.status}:${payment.amount_refunded || 0}`, 'checkout.verified', c.get('user').id); return c.json(result) })
api.post('/payments/webhook', async c => { if (!c.env.RAZORPAY_WEBHOOK_SECRET) fail(503, 'Payment webhook is not configured.'); const raw = await c.req.text(); if (raw.length > 65536) fail(413, 'Payload too large.'); const signature = await hmac(c.env.RAZORPAY_WEBHOOK_SECRET, raw); if (!equal(signature, c.req.header('x-razorpay-signature') || '')) fail(400, 'Invalid webhook signature.'); const b = JSON.parse(raw); const eventId = c.req.header('x-razorpay-event-id') || await sha(raw); const eventType = String(b.event || ''); const paymentId = b.payload?.payment?.entity?.id || b.payload?.refund?.entity?.payment_id || b.payload?.dispute?.entity?.payment_id; if (!paymentId || !/^[a-zA-Z0-9_]+$/.test(paymentId)) return c.json({ ignored: true }); if (!c.env.RAZORPAY_KEY_ID || !c.env.RAZORPAY_KEY_SECRET) fail(503, 'Payment reconciliation credentials are missing.'); const payment = await razor(c.env, 'payments/' + paymentId); return c.json(await reconcilePayment(c, payment, eventId, eventType)) })
api.get('/payments/history', auth, async c => { const { results } = await c.env.DB.prepare('SELECT id,amount,currency,status,created_at FROM payment_orders WHERE user_id=? ORDER BY created_at DESC').bind(c.get('user').id).all(); return c.json({ orders: results }) })
api.all('/admin/*', auth, c => c.json({ error: 'Administrative operations are disabled until administrator provisioning, MFA, and moderation workflows are implemented and reviewed.' }, 503))
api.notFound(c => c.json({ error: 'API endpoint not found.' }, 404))
api.onError((err, c) => { if (err instanceof HTTPException) return c.json({ error: err.message }, err.status); if (err instanceof SyntaxError) return c.json({ error: 'Invalid JSON request.' }, 400); if (String(err.message).includes('booking_overlap')) return c.json({ error: 'That time overlaps an accepted booking. Choose another time.' }, 409); if (String(err.message).includes('UNIQUE constraint')) return c.json({ error: 'This operation has already been recorded. Refresh and try again.' }, 409); const requestId = id(); console.error(JSON.stringify({ level: 'error', requestId, path: c.req.path, kind: err.name })); return c.json({ error: 'We could not complete that request. Please try again.', request_id: requestId }, 500) })
